### ISSUE TITLE
`cargo run` fails

### ISSUE THREAD

**Issue by pranitbauva1997** [amitu/realm-starter#5]
After setting up the `nix-shell`, I tried executing `cargo run` to verify whether the setup has been done properly but a few errors occurred.

First one:

```
error: failed to load source for a dependency on `realm`

Caused by:
  Unable to update /home/amit_project/Code/amitu_heroku/realm

Caused by:
  failed to read `/home/amit_project/Code/amitu_heroku/realm/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I fixed this by modifying [these two lines](https://github.com/amitu/realm-starter/blob/1e1d7dbf43a97dabc4714e39061201d810e354e8/Cargo.toml#L7-L8) by removing `amitu_heroku/` from the start of the string and by cloning the [ackotech/realm](https://github.com/ackotech/realm) in the parent folder. On fixing this and running the command again, I got the error:

```
error: failed to load source for a dependency on `observer`

Caused by:
  Unable to update /home/amit_project/Code/observer/observer

Caused by:
  failed to read `/home/amit_project/Code/observer/observer/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

This is again fixed by cloning [ackotech/observer](https://github.com/ackotech/observer) in parent folder and thankfully it proceeds further by downloading and compiling dependencies until it gets stuck again throwing the error:

```
error: failed to run custom build command for `onig_sys v69.2.0`

Caused by:
  process didn't exit successfully: `/home/amit_project/Code/realm-starter/target-nix/debug/build/onig_sys-a98bff8bff7459a6/build-script-build` (exit code: 101)
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:983
  15: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__static_ref_initialize
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1711
  16: core::ops::function::FnOnce::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/ops/function.rs:232
  17: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31
  18: std::sync::once::Once::call_once::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/sync/once.rs:264
  19: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:417
  20: std::sync::once::Once::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/sync/once.rs:264
  21: lazy_static::lazy::Lazy<T>::get
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30
  22: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__stability
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/<::lazy_static::__lazy_static_internal macros>:16
  23: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/<::lazy_static::__lazy_static_internal macros>:18
  24: bindgen::ensure_libclang_is_loaded
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1718
  25: bindgen::Bindings::generate
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1733
  26: bindgen::Builder::generate
             at /home/amit_project/Code/realm-starter/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.50.1/src/lib.rs:1228
  27: build_script_build::bindgen_headers
             at ./build.rs:189
  28: build_script_build::compile
             at ./build.rs:64
  29: build_script_build::main
             at ./build.rs:229
  30: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  34: std::panicking::try
             at src/libstd/panicking.rs:270
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  37: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  38: main
  39: __libc_start_main
  40: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

which seems difficult to debug for me and understand what's happening.

**Comment by amitu** [comment]
Try `gsub update` instead of manually cloning the ackotech/realm repo.

**Comment by amitu** [comment]
We use `gsub` to clone other repos (instead of `git submodule`). 

For missing clang, refer to this issue: https://github.com/NixOS/nixpkgs/issues/52447 and see if it helps.

**Comment by pranitbauva1997** [comment]
`clang` is not available by default in Linux and thus I added `clang` & `llvm` to the list named `nativeBuildInputs` in `shell.nix` and set the environment variable `LIBCLANG_PATH="${llvmPackages.libclang}/lib"` which fixes this error after which I stumble upon another error:

```
]pungi-man-thinkpad% cargo run
   Compiling onig_sys v69.2.0
   Compiling onig v5.0.0
   Compiling syntect v3.3.0
   Compiling realm v0.1.18 (/home/amit_project/Code/realm)
error: custom attribute panicked
  --> /home/amit_project/Code/realm/src/response.rs:11:1
   |
11 | #[observed(with_result, namespace = "realm__response")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: Could not find observer.json

error: aborting due to previous error

error: could not compile `realm`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by pranitbauva1997** [comment]
This issue is solved by including `observer.json` file in the root directory.
